### ISSUE TITLE
Move paging controller into common module

### ISSUE THREAD

**Issue by msfjarvis** [msfjarvis/compose-lobsters#257]
Currently the paging logic used to load stories from lobste.rs is centralized in the `android` module [here](https://github.com/msfjarvis/compose-lobsters/blob/ff64c9b3a408c717081f261597e69fbe8979dd08/android/src/main/kotlin/dev/msfjarvis/claw/android/paging/LobstersPagingSource.kt) and [here](https://github.com/msfjarvis/compose-lobsters/blob/ff64c9b3a408c717081f261597e69fbe8979dd08/android/src/main/kotlin/dev/msfjarvis/claw/android/viewmodel/ClawViewModel.kt#L27).

With the [ongoing work](https://github.com/kuuuurt/multiplatform-paging/pull/21) to make [multiplatform-paging](https://github.com/kuuuurt/multiplatform-paging) work on the JVM, moving the paging controller to the `common` module would simplify the introduction of real, paging-backed data into the `desktop` module (current WIP branch can be found [here](https://github.com/msfjarvis/compose-lobsters/tree/desktop-paging)) when the next multiplatform-paging release happens.

**Comment by Skrilltrax** [comment]
I can try 👀

**Comment by msfjarvis** [comment]
I've published my fork of multiplatform-paging to the Sonatype snapshots repository and merged `desktop-paging`﻿into `main`. This removes the hurdle of having to publish a copy of multiplatform-paging to `mavenLocal` to build the desktop project.

**Comment by msfjarvis** [comment]
multiplatform-paging v0.4.5 is now out with JVM support https://github.com/kuuuurt/multiplatform-paging/releases/tag/v0.4.5

**Comment by msfjarvis** [comment]
Blocked on https://github.com/kuuuurt/multiplatform-paging/pull/26

**Comment by msfjarvis** [comment]
With the switch to moko-paging in #313, now blocked on https://github.com/icerockdev/moko-paging/issues/55
