### ISSUE TITLE
Support listing posts by tag

### ISSUE THREAD

**Issue by msfjarvis** [msfjarvis/compose-lobsters#331]
### Relevant endpoints

- All tags: https://lobste.rs/tags.json
- Posts by tag: https://lobste.rs/t/rust.json

### Additional info

Tags can be combined in an `OR` fashion, so posts tagged both `plt` and `rust` can be fetched at `https://lobste.rs/t/plt,rust.json`.

**Comment by msfjarvis** [comment]
Don't really think I want this anymore

**Comment by soo-shan** [comment]
This seems like a good feature to have since tags are already there. Any specific reason not to have this ?

**Comment by msfjarvis** [comment]
> This seems like a good feature to have since tags are already there. Any specific reason not to have this ?

Couldn't think of a good enough UI at the time, plus the search functionality lets you use `tag:<tag name>` to filter results so it's a relatively acceptable compromise.
