### ISSUE TITLE
Option to import/export saved posts

### ISSUE THREAD

**Issue by dipeshkaphle** [msfjarvis/compose-lobsters#381]
Hi, I wanted to know if there's a way to import/export saved post list. I saw there was a PR for it (#159), but there's really no option in the app.

**Comment by msfjarvis** [comment]
That PR was for an older iteration of the app, the currently developed branch was rebuilt from scratch and doesn't have the feature.

I'll try and see if I can forward port the old code.

**Comment by dipeshkaphle** [comment]
Thanks a lot. Love the app btw, it's very nice and clean. Very nice work

**Comment by msfjarvis** [comment]
I've [added support for backup and restore](https://github.com/msfjarvis/compose-lobsters/compare/f102166fae8bd843f7e043a0457115cc6501bab2...3738d94789ce2b74d3132e8cd135a178fa40018d) of saved posts, the UI and UX is a bit rushed so I'll take some time to polish that before it's headed to Google Play. In the mean time you can grab the snapshot build from [here](https://github.com/msfjarvis/compose-lobsters/releases/tag/nightly) once it's done building.
