### ISSUE TITLE
post search

### ISSUE THREAD

**Issue by Wjxfi** [msfjarvis/compose-lobsters#386]

**Comment by msfjarvis** [comment]
Lobsters has no JSON API for search and I do not care for parsing HTML so this will not happen anytime soon.

**Comment by msfjarvis** [comment]
I started hacking on this and it might not be too bad to implement after all.

**Comment by msfjarvis** [comment]
https://github.com/msfjarvis/compose-lobsters/commit/e651c122125d

The search "backend" is functional now, I'll wire this into the existing API layer in the morning and try to build up the UI over the next couple weeks.

**Comment by msfjarvis** [comment]
https://github.com/msfjarvis/compose-lobsters/commit/01699b9fab5d83316fa879f3045e9c667a9227cf

API integration is complete

**Comment by msfjarvis** [comment]
Fixed by 84c9dd376212699f43ace5e79025538b5b9c25de 5e91e20c512b5c7a1eb2d92d9e1e3b9aa2a52d6a 8d6aba986536ff2685ce20ebc6dbe0bb60c6dabe and d3c3e3ca089a21620f17b8b96d4f8c340c4e80d7

All goes well, this'll be released in a week or so after some UI polish.

**Comment by msfjarvis** [comment]
This is now out in https://github.com/msfjarvis/compose-lobsters/releases/tag/v1.31.0, will be available on Google Play in a few hours.
