### ISSUE TITLE
Introduce a different style to read posts

### ISSUE THREAD

**Issue by janilowski** [msfjarvis/compose-lobsters#394]
Hi,
I think it would be useful if the posts a user has already clicked on would appear in a font that isn't **bold** and perhaps a more muted color.

This would require keeping an infinitely expanding index of clicked posts, so maybe a mechanism removing entries older than 365 days at startup could also be of use.

**Comment by msfjarvis** [comment]
The app already does that for comments, adding an unread badge to comment entries that were added since the last visit but I didn't feel a need for this to extend to posts themselves. I'll try it out and see how I like it.

**Comment by msfjarvis** [comment]
This was released in https://github.com/msfjarvis/compose-lobsters/releases/tag/v1.34.0
