### ISSUE TITLE
Compact Mode

### ISSUE THREAD

**Issue by tywil04** [msfjarvis/compose-lobsters#526]
Title.

On my phone I get 5.5 posts and they have a lot of (unnecessary) white space, I think it would be beneficial to have a compact mode where action buttons are removed, text is smaller etc.

**Comment by msfjarvis** [comment]
I've made some changes to the default layout, they'll be available in the Google Play open testing channel in 6-7 hours when the scheduled nightly build is triggered. You can find links to sign up for it in the README.

**Comment by msfjarvis** [comment]
![Screenshot_20240421-025355.png](https://github.com/msfjarvis/compose-lobsters/assets/13348378/6c8ec238-2079-4e59-882d-32e3cddf1470)

It's available in the open testing channel now.
