### ISSUE TITLE
OLED Dark Theme

### ISSUE THREAD

**Issue by tywil04** [msfjarvis/compose-lobsters#527]
Title.

My phone (like many others) has an OLED screen where black means the pixels are off. This not only conserves battery life but looks better. I think there should be a toggle to enable OLED mode so when in dark mode the main background of the app is black.

**Comment by msfjarvis** [comment]
I personally don't like full black themes and the app intentionally does not have any configuration knobs, so even building it in as an option adds in a fair amount of preparatory work that I'm not interested in doing.
