### ISSUE TITLE
Saving posts causes lists to refresh and lose scroll position 

### ISSUE THREAD

**Issue by surajsharma** [msfjarvis/compose-lobsters#558]
Adding an article to saved makes the list scroll in a wierd way

**Comment by msfjarvis** [comment]
I'm aware of the issue, it's a workaround for the AndroidX Paging library not having support for updating its cached item list without a full network refresh. I've [started working](https://github.com/msfjarvis/compose-lobsters/compare/main...hs/cache-paging-data) on a solution but it'll take some time to get it right.

**Comment by msfjarvis** [comment]
Dropping a quick update on this, I was unable to get AndroidX Paging to do what I was looking for so I've [started migration](https://github.com/msfjarvis/compose-lobsters/tree/hs/newest-posts-store) the app's data layer to [Store](https://github.com/MobileNativeFoundation/Store) which natively supports offline-first operations. However, their paging API is currently unstable and due for a massive overhaul [very soon](https://github.com/MobileNativeFoundation/Store/discussions/642#discussioncomment-9744767) so progress here is stalled for a bit until they release the new API.

**Comment by msfjarvis** [comment]
That's a pretty unnecessary detail to throw into a thank you message but sure...
