### ISSUE TITLE
Improve tablet support

### ISSUE THREAD

**Issue by msfjarvis** [msfjarvis/compose-lobsters#671]
The [material3-adaptive](https://developer.android.com/jetpack/androidx/releases/compose-material3-adaptive) library has enough functionality in it now to be able to integrate it into Claw. Ideally this would simply keep the current home screen UI as the main "pane" and open the comments page in the details pane.

**Comment by ThanaReka** [comment]
Hi @msfjarvis!  I would like to work on this issue if it's open to contributions.

**Comment by msfjarvis** [comment]
> Hi @msfjarvis! I would like to work on this issue if it's open to contributions.

It absolutely is!

**Comment by ThanaReka** [comment]
To clarify, are you looking to incorporate the TwoPaneScaffold to display the list of posts and the comments pane next to each other?

**Comment by msfjarvis** [comment]
> To clarify, are you looking to incorporate the TwoPaneScaffold to display the list of posts and the comments pane next to each other?

Yep exactly that.

**Comment by msfjarvis** [comment]
Hey @ThanaReka are you still working on this? If you're no longer interested I can unassign you so someone else can take a stab at it instead.

**Comment by ThanaReka** [comment]
Hi @msfjarvis!  Sorry this is taking longer than I expected.  I would like to continue working on this issue and get to the bottom of it in the next day or two.

**Comment by msfjarvis** [comment]
> Hi @msfjarvis! Sorry this is taking longer than I expected. I would like to continue working on this issue and get to the bottom of it in the next day or two.

No rush on my end, was just checking in. Feel free to put up an incomplete draft if you need help with anything!

**Comment by msfjarvis** [comment]
> Actually, I have another question for you since I had time to properly look at your code today. I believe that the best suited layout would be the ListDetailPaneScaffold, but not sure whether to incorporate it in the LobstersPostsScreen or the NetworkPosts composable. What would you recommend @msfjarvis ?

You can spin up a new screen entirely and check the window size class in `MainActivity` itself to decide whether to launch `LobstersPostsScreen` or the `ListDetailPaneScaffold` version.
