### ISSUE TITLE
Tablet doesn't have the navigation bar after the new update 

### ISSUE THREAD

**Issue by dipeshkaphle** [msfjarvis/compose-lobsters#723]
![Screenshot_2024-11-30-10-53-05-30_ab514cdf237be04258f08c3cc585b5db](https://github.com/user-attachments/assets/a0da63fe-42cb-4502-99e5-90e9b3a120db)

I don't see navbar at all, this happened after the new update.

My device is OnePlus pad.

**Comment by msfjarvis** [comment]
Oh how did I fuck that up 🤦🏼 

Will get a fix out today

**Comment by msfjarvis** [comment]
I've pushed out the changes to reintroduce the navigation rail for tablets, here are some screenshots. I'm also going to manually trigger a new open beta build, if you want to help test this out before a full release you can opt into the beta from the links in the README and let me know.


![Screenshot_20241130_081909](https://github.com/user-attachments/assets/c0aaa0ff-a92f-4899-9b9e-34a9f62241a8)
![Screenshot_20241130_081853](https://github.com/user-attachments/assets/fc60ebc6-8bfe-4828-b9d9-14332bdc50de)

**Comment by dipeshkaphle** [comment]
Aah no worries. I've signed up for beta, glad to help. Thanks a lot.

**Comment by msfjarvis** [comment]
I've triggered a new stable release, it'll be uploaded to Google Play in the next 15 minutes and become available in a couple hours tops. Thanks for the report!
